### PR TITLE
Split indicator algorithms from rendering to enable re-use

### LINKED ISSUE #239: Split indicators into model and view components

### PR DESCRIPTION
**Pull request by chrisprice**
Fixes #239

### CODE REVIEW

**Comment by chrisprice** [comment]
FYI the rsi algorithm might be a bit sketchy, we need some real data to test this with.

**Comment by chrisprice** [comment]
Also need to change the RSI to use annotations rather than lines now that they've landed in master.

**Comment by chrisprice** [comment]
> Also need to change the RSI to use annotations rather than lines now that they've landed in master.

Done

**Comment by ColinEberhardt** [comment]
The RSI looks good to me - I guess this is the exponential moving average flavour, rather than the SMA.

We've actually got a book in the office which has test data for a range of studies.

**Pull request merged**
