### PR TITLE
Add transition support to bar series

### PR DESCRIPTION
**Pull request by jleft**
This might be a bit early to merge, but it shows a basic example of how to add transition support to a component. There is an accompanying visual test to demonstrate its behavior. See #212.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Thanks for this - great job :-) I'm glad to see that there wasn't much work involved in adding transition support. A few random comments ...

I see you are using `d3.transition(selection)` rather than `selection.transition()` - is there a particular reason for this?

In order to make the transition configurable are you planning on adding duration and ease properties to the series?

One significant drawback of this change is that the bars always fade in, I guess the series could be implemented such that if the duration is set to zero, that no transitions are applied to the selections.

It's great that decorations are also transitioned as well :-) Could you also use this to update the enter selection so that bars grow from the bottom of the screen upwards when the first enter? And 

@chrisprice when you added your simplified data-join I think you mentioned that it required a parent `g` for each element in the series? It is probably worth checking that this works with the transitions as expected.

**Comment by chrisprice** [comment]
I'm guessing the growing transition could be added by a decorator on the
(fake) enter selection?

What's the behaviour of a transition selection if you chain 2 calls to
update the same attribute? If it just overrides the old value (rather than
transition to it) then decorate could also be used to customise the
transition. Just a thought...

Is it possible to define different times for the enter, update, exit
transitions?

I suppose I'm trying to get to the bottom of whether transitions have to be
an all or nothing row affair.

**Comment by chrisprice** [comment]
...and I agree about testing with simple data join. As it's pretty much a
one liner, any chance you could give it a go James?

**Comment by ColinEberhardt** [comment]
> What's the behaviour of a transition selection if you chain 2 calls to 
update the same attribute? If it just overrides the old value (rather than 
transition to it) then decorate could also be used to customise the 
transition. Just a thought... 

Yes, I tried this, you can specify the same attribute value twice. The last value is the one that gets used, so ideal for our plans with decorate.

**Comment by jleft** [comment]
> Thanks for this - great job :-) I'm glad to see that there wasn't much work involved in adding transition support.

No problem, thank you :-)

> I see you are using d3.transition(selection) rather than selection.transition() - is there a particular reason for this?

Yes - in this context, within a component, `selection.transition()` would apply the same, default transition every time - regardless of whether the component was called on a selection or transition.

`d3.transition(selection)` allows the user to call the component on a transition and the transition's properties (duration, delay, ease) will be inherited by the component; it also means if a selection (with no transitions) is passed to the component, the component will function as expected but with no transitions applied. See the following on [`d3.transition()`](https://github.com/mbostock/d3/wiki/Transitions#d3_transition):

> When called with an optional selection, this method typically returns the specified selection; i.e., it is a no-op. However, within the context of transition.each, this method will create a new transition for the specified selection that inherits the delay, duration and other properties of the parent transition. This is useful for implementing reusable components that can be called either on selections or on transitions, in the latter case supporting deriving concurrent transitions. An example of this is D3’s axis component.
-- *https://github.com/mbostock/d3/wiki/Transitions#d3_transition*

<br>

> In order to make the transition configurable are you planning on adding duration and ease properties to the series?

This is already supported. The transitions in the component will inherit the properties of the transition which it is called upon, the following properties would be applied to the transition in the component:

```js
// delay, duration and ease would be inherited by the bar component's transitions
chartLayout.getPlotArea()
    .datum(data)
    .transition()
    .delay(1000)
    .duration(2500)
    .ease('bounce')
    .call(bar);
```

> One significant drawback of this change is that the bars always fade in, I guess the series could be implemented such that if the duration is set to zero, that no transitions are applied to the selections.

If called on a transition this is true, but if called upon a selection no transitions would be applied (including the fade in). Setting the duration to 0 would also have the same effect.

```js
//  Bars would not fade in
chartLayout.getPlotArea()
    .datum(data)
    .call(bar);
```

> It's great that decorations are also transitioned as well :-) Could you also use this to update the enter selection so that bars grow from the bottom of the screen upwards when the first enter?

> I'm guessing the growing transition could be added by a decorator on the (fake) enter selection?

I think so, but I'm not certain, I'll try this out.

> Is it possible to define different times for the enter, update, exit transitions?

Not currently. I'm hoping this can be achieved using _named transitions_ - I'm going to look into this.

> ...and I agree about testing with simple data join. As it's pretty much a
one liner, any chance you could give it a go James?

Sure :-)

---

I think I covered everything... let me know if I've missed anything!

**Comment by chrisprice** [comment]
By the looks of it, adding the transition selection into simpleDataJoin works :+1: 

There are two remaining shortcomings -

* Whilst it is possible to override any exit transitions e.g. to remove the fade out, the elements themselves will still only be removed once the transition has completed. This can lead to some strange behaviour although it's probably work-around-able by toggling the visibility of the element or somesuch.
* The update and exit transitions share the same transition settings (i.e. duration, easing function). It may be possible to fix this with named transitions but I don't think @jleft had much luck with that.

Having now enumerated the shortcomings, I'm not actually convinced that either of them are very restrictive. I think we should spend some time establishing whether it is possible to solve them but I don't think they should ultimately block this solution.

**Comment by jleft** [comment]
@chrisprice - thanks for comments, I agree with all of the above :+1: 

> The update and exit transitions share the same transition settings (i.e. duration, easing function). It may be possible to fix this with named transitions but I don't think @jleft had much luck with that.

No luck so far, but I'm going to have a deeper look into how the transitions are implemented and try out a few other ideas too.

**Comment by chrisprice** [comment]
Is this ready to merge (apart from the conflicts)? I think there's general acceptance of (read silence on this thread about) the shortcomings identified above, so I think it should go in.

**Comment by jleft** [comment]
> Is this ready to merge (apart from the conflicts)?

Yes, I think so! :-)

**Comment by chrisprice** [comment]
Nice one!

**Pull request merged**
