### PR TITLE
WIP: Separate out line area point

### PR DESCRIPTION
**Pull request by chrisprice**
As an alternative to putting area and point into line, separating them all out so that they can be used by the indicators?

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Nice job, just had a quick skim through the code, all looks good to me. I agree that area should have properties of `yValue` and `y0Value` - and the functor concept works **very** well here, allowing you to set a constant, to shift the baseline, or supply a function that turns this into a band.

This should definitely be rolled out to bar as well :-)

I hacked around with decorate a bit, and all works well:

image

Code:

```
var point = fc.series.point()
    .xScale(dateScale)
    .yScale(priceScale)
    .yValue(fc.utilities.valueAccessor('close'))
    .decorate(function(sel) {
        sel.select('circle')
            .attr('style', 'fill: red')
            .attr('r', function(d) {return (d.high - d.low) * 10; });

        sel.append('text')
            .attr('x', function(d) { return dateScale(d.date); })
            .attr('y', function(d) { return priceScale(d.close); })
            
            .text(function(d) { return d.close.toFixed(0); });
    });
```

My only thought is, now that we have a group element (courtesy of simple data-join), I think it would be better if bar and point series positioned their elements using a translate on the group. 

With the example above, where I am adding text to each point, the x & y attributes of the text element would simply be an offset from the origin of each datapoint location, so no need to mess about with scales.

**Comment by chrisprice** [comment]
Good stuff :+1: 

I'd thought about something similar but initially dismissed it to support someone who wanted to use only the x value and fix y at some pixel position (or vice versa). However, thinking about it that's a very niche edge case. Also, if they wanted to do that, they could always just use the scale to apply the opposite offset.

**Comment by chrisprice** [comment]
Created #258 to cover the above improvement.

**Comment by chrisprice** [comment]
I think that means this can go in unless there are any objections?

**Comment by ColinEberhardt** [comment]
Yep, looks good to me

**Pull request merged**
