### PR TITLE
Extract SVG path generator from candlestick/ohlc series. 

### LINKED ISSUE #354: Split path string generators out of ohlc and candlestick series
They can be re-used in other ways, the series should just combine scales with renderers.

### PR DESCRIPTION
**Pull request by chrisprice**
Fixes #354.

I think it's ultimately the right thing to do but the fake index stuff is horrible. Can anyone think of a better way?

### CODE REVIEW

**Comment by chrisprice** [comment]
I've removed the fake index stuff in c8bec0c. I'm happy with it now, let me know what you think.

**Comment by jleft** [comment]
:+1:

**Comment by ColinEberhardt** [comment]
:+1: from me ... although it is a shame that there is so much duplication of the configuration properties. Could the pathGenerator properties be re-bound onto candlestick / ohlc? Although I guess an issue here is that the path generator has is stateful.

@jleft / @chrisprice  - it would be great if one of you could a few notes to `simpleDataJoin` that describes what it does and why it exists!

**Comment by chrisprice** [comment]
Good point, added #366 to track the simpleDataJoin documentation.

**Comment by chrisprice** [comment]
As discussed the value accessor index arguments prevent simple re-binding. The svg path generators operate on each data item individually so would always pass an index of 0.

**Pull request merged**
