### PR TITLE
Bar series update (translate data point groups in series)

### PR DESCRIPTION
**Pull request by jleft**
See #258

### CODE REVIEW

**Comment by chrisprice** [comment]
I know we talked about translating to the most appropriate location for the series i.e. where would it be most helpful to have the origin for transitions. Have you specifically chosen the location in this case?

There's a few too/to typos, not actually yours but whilst you're correcting grammar :)

**Comment by jleft** [comment]
As discussed, the origin of each group is now translated to the centre (horizontally and vertically) of its corresponding bar (changed in 61945c7); illustrated by the white crosses:

bar-origin

I'd anticipate that most translations from this point will take into account the height and/or width or the bar. When I've tried adding some elements using decorate, this it felt a bit awkward, for example, (unless I'm missing something!) to translate a text label to the top of a bar, you'd have to perform a y-translation like this: `-(yScale(0) - yScale(d.age)) / 2`. I wonder if there is a more elegant solution, maybe exposing a couple of functions for the height and width of each bar would be useful?

**Comment by ColinEberhardt** [comment]
@jleft - #373 has now added the correct translation, and has a test which shows the 'origin' of each datapoint.

I still need to add transition support back in!

**Comment by jleft** [comment]
> @jleft - #373 has now added the correct translation, and has a test which shows the 'origin' of each datapoint.

Looks really good! I'll close this PR now.

> I still need to add transition support back in!

Cool, I'm happy to look into/help with this, if that would be useful?

**Comment by ColinEberhardt** [comment]
> > I still need to add transition support back in!
> Cool, I'm happy to look into/help with this, if that would be useful?

That would be great - thanks. Hopefully now that the series are all rendered in a similar fashion it should be easy to add transition support to all of them.

**Pull request closed without merging**
