### PR TITLE
Update Candlestick series to use path

### PR DESCRIPTION
**Pull request by jleft**
Each candle is now drawn using a single `path`, rather than a `rect` and a `line`. This feels like the more idiomatic solution to me, and will lead to much more intuitive transitions.

### CODE REVIEW

**Comment by tlsim** [comment]
:+1:

**Comment by chrisprice** [comment]
Thanks @jleft!

**Comment by chrisprice** [comment]
Need to learn how to use GitHub... 

Looks like there are some merge conflicts, any chance you could take a quick look?

**Comment by jleft** [comment]
No problem, will do!

**Comment by jleft** [comment]
Having looked at this again, the wick doesn't look great with transitions, so may need a small tweak - I'll look into this.

I've also done some work on a nicer API for low-level path data, which should make to code more readable - I'll try to get this in soon.

**Comment by chrisprice** [comment]
Merging as is for now, we can work on the transition support separately.

**Pull request merged**
