### PR TITLE
Add developing instructions to README

### PR DESCRIPTION
**Pull request by jleft**
Feedback encouraged! :)

I've tried to cover the important parts clearly and fairly concisely. Does it all make sense? Is there anything missing? Anything superfluous?

### CODE REVIEW

**Comment by janakerman** [comment]
I think that's at a suitable level of detail!

**Comment by ColinEberhardt** [comment]
Looks good :-)

One thing though, this documents how to build, etc ... but what next? I think the final step should be to direct them to the visual tests.

Thanks.

**Comment by ColinEberhardt** [comment]
Ah - I see you'd already thought of this :-)  #305

**Comment by chrisprice** [comment]
Thanks @jleft

**Pull request merged**
