### PR TITLE
OHLC now has a single render mode

### LINKED ISSUE #210: OHLC has three render modes, keep? or simplify?
Currently the OHLC series has three different methods that can be used to render the series, each one having a different performance characteristic.

Do we want to keep this feature or not?

If we do keep it, we need to make it more obvious what this feature does. By choosing the more high-performance version I presume you sacrifice some functionality?

Ideally I'd like to see an equivalent visitor function as per #202

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Closes #210

### CODE REVIEW

**Comment by jleft** [comment]
Looks good :+1: 

It looks like a visual test has been added (an shown in the HTML), but the JavaScript for it hasn't - is this script to be added before the merge?

**Comment by ColinEberhardt** [comment]
Thanks @jleft well spotted. I've added the missing file.

**Comment by jleft** [comment]
> Thanks @jleft well spotted. I've added the missing file.

No problem :-). Though, it looks like that commit (01a8498) actually made a change to the source of the component, rather than adding the missing file.

**Comment by ColinEberhardt** [comment]
> No problem :-). Though, it looks like that commit (01a8498) actually made a change to the source of the component, rather than adding the missing file.

Yeah, that was a hasty, just about to leave the office, commit. Embarrassingly rectified later ... https://github.com/ScottLogic/d3-financial-components/commit/44b6c8fd7cbbbafc51d1b1aeeef81f70917380ee

**Pull request merged**
