### PR TITLE
Added a layout function to d3.selection.

### PR DESCRIPTION
**Pull request by ColinEberhardt**
See #274 

Thanks for the ideas @chrisprice - I added a more complex example, and found the `layout` function to be really quite versatile and easy to use.

### CODE REVIEW

**Comment by chrisprice** [comment]
On mobile so can't comment inline. 

* Consider changing type checks to be positive rather than negative with errors thrown? (Here's looking at you d3!!)
* Can we special case a coercion to number for reading back width/height values? That's just caught me out in a horrible way!
** Just thought about x/y, how can we help with those?

**Comment by chrisprice** [comment]
What about rect/svg or are you leaving that to me?

**Comment by ColinEberhardt** [comment]
> Consider changing type checks to be positive rather than negative with errors thrown? (Here's looking at you d3!!)

I'm all for better error reporting with D3FC (and D3) - although we do need to decide on what mechanism to use for reporting errors.

> What about rect/svg or are you leaving that to me?

No, I'm happy to do that. Although I'd prefer to tackle things via multiple PRs rather than one big one, so just keep the issue open rather than closing it.

**Comment by jleft** [comment]
Looks good :+1: 

Conflicts resolved and merged in #294.

**Pull request closed without merging**
