### PR TITLE
Upgrade D3 to 3.5.4

### LINKED ISSUE #286: Upgrade to d3 v3.5.4
For more details see #280 (i.e. unwind the changes made as part of that issue).

### PR DESCRIPTION
**Pull request by jleft**
Resolves #286

### CODE REVIEW

**Comment by chrisprice** [comment]
Thanks James! Should d3 and layout not be made full blown deps rather than dev deps?

**Comment by jleft** [comment]
No problem! Good point, agreed - fixed in 2c018b6

**Comment by chrisprice** [comment]
:lgtm:!

**Comment by chrisprice** [comment]
Mobile emoticon fail :(

**Pull request merged**
