### PR TITLE
Comparison series updates

### LINKED ISSUE #28: Documentation: Comparison series

### PR DESCRIPTION
**Pull request by tlsim**
- Removed ordinal colour scale (use css instead)
- No longer have to specify series names. Data input is now an array of data arrays.
- Configurable x and y values using valueAccessor #130 #105 
- Like d3 brush / axis, store element specific state on `__chart__`
  This allows for using a single instance of the component to create multiple charts which are independently interactive on zoom.
- Add JSDoc. Closes #28

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Thanks for the update - I was wondering, do you have a test page that demonstrates some of these updates / new features? If so, perhaps you could share in a comment or gist?

I think @jleft is currently pulling together a test page. Would be good to integrate your tests into this.

**Comment by ColinEberhardt** [comment]
Does this update result in an AVG structure that mirrors the other components as per #147 ?

**Comment by tlsim** [comment]
> Does this update result in an SVG structure that mirrors the other components as per #147 ?

Yes.

Here's an example which uses a single instance of fc.series.comparison to make 2 independent interactive charts. https://gist.github.com/tlsim/932320b54d9b725b440a

**Comment by tlsim** [comment]
superseded by #279

**Pull request closed without merging**
